### PR TITLE
ENTSWM-202: Update to Swarm 7.0.0.redhat-8

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Review by kenfinnigan — COMMENTED** [review]
Does adding commons-logging to each sub module cause issues with community version of booster? Does the dependency need to be added into pom-redhat.xml and inherited by sub modules?

**Comment by heiko-braun** [comment]
@kenfinnigan The latest commit moves the dep management to parent. I think this is the best we can get without creating a separate prod branch. The issue is the parent def in the `greeting` and `name` modules. They point to specific versions and these are different in community and prod.

**Comment by kenfinnigan** [comment]
Not sure what you mean about different versions as both are currently using 1.1.1 of commons-logging.

I may not have been clear with what I was meaning previously. I was suggesting to add the commons-logging as a test dependency into the root pom-redhat.xml, not into the dependencyManagement section.

That way commons-logging is available to the name and greeting modules without additional dependencies, and is contained within pom-redhat.xml only

**Comment by heiko-braun** [comment]
@kenfinnigan Thanks, I now see what you mean. The latest commit reflects that change

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
