### PR TITLE
[SWARM-1856,SWARM-1884] wfs-circuite-breaker pom updates

### PR DESCRIPTION
**Pull request by sberyozkin**
1. Updated the swarm version to 2018.3.3
2, Updated the parent version to 18

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
The failure after last commit is caused by the `version.override.jackson` property removal. In the `-redhat` variant, the top-level POM contains this property as well, so it's fine there.

But actually! The community variant of this booster (and actually of any WildFly Swarm booster) _doesn't_ need to do the Jackson version override, so I'd just delete everything from https://github.com/sberyozkin/wfswarm-circuit-breaker/blob/1f51d0218e97728d3e260b28a99f42450caf010f/tests/pom.xml#L139 to the very end, except of specifying the `integration-test` and `verify` goals.

**Review by Ladicek — CHANGES_REQUESTED** [review]
Please remove the entire Jackson override stuff. That should make the tests pass.

**Comment by sberyozkin** [comment]
Oops, I did not even check yesterday if this property was used; good plan though to remove all the related info after all :-)

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I've changed the job to use a higher timeout. The OpenShift cluster the tests run on seems sluggish nowadays.

retest this please

**Comment by Ladicek** [comment]
Now this sounds like an actual test issue. I mean -- probably an issue in the test, but I'll have to look.

**Comment by Ladicek** [comment]
retest this please

**Pull request merged**
