### PR TITLE
Release V1

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
@kenfinnigan If you by chance read this, it would be helpful if you could merge the updates to release v1 of the booster

**Comment by ALRubinger** [comment]
@heiko-braun I'm totally cool with having basically anyone review and merge this if you want it to make this upcoming train.  Worst case scenario: it sucks and we fix it for the next train.  If you're feeling super uncertain about it, I'm also cool with your holding it to the next release.  Your call.

**Comment by heiko-braun** [comment]
Closing this as out-of-date.

**Review by heiko-braun — COMMENTED** [review]
@kenfinnigan I can only comment, but not approve

**Comment by kenfinnigan** [comment]
reclosing

**Pull request closed without merging**
