### PR TITLE
[SWARM-1913] Removing the redundant assemblies

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
-Popenshift-it passes locally

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
The underlying OpenShift cluster is just too slow to start containers :-(

**Pull request merged**
